### ISSUE TITLE
Can we set both Thiol- and sulfenic acid- form in the HeavyFragment?

### ISSUE THREAD

**Issue by helloworld1631** [diogobor/Scout#1]
Hi,

I am wondering if can set both unsaturated thiol and sulfenic acid as the heavy fragment modification. Do you think it will increase the identification number?

Thank you!

**Comment by diogobor** [comment]
Hello, 

The current architecture of Scout does not allow to set both unsaturated thiol and sulfenic acid as the heavy fragment modification. 
For the current version, my idea would be performing two searches: 1) setting up the unsaturated thiol as heavy frag modification and 2) setting up the sulfenic acid as heavy frag modification. At the end, merge both results.

In terms of increasing the identification number, I don't think this strategy will significantly increase the number of IDs, since the tendency to observe neutral losses in the most current mass spectrometers is smaller, mainly when HCD is used to acquire the dataset.

Best,
Diogo
