### ISSUE TITLE
Compatibility with XiViewer

### ISSUE THREAD

**Issue by FriedLabJHU** [diogobor/Scout#8]
Would it be possible to have an option to export data in a way that is compatible with XiView? It would make for an extermely streamlined crosslinking analysis workflow!

**Comment by diogobor** [comment]
Hello @FriedLabJHU ,
Yes. It has an option to export Scout results in mzID 1.2 and mzID 1.3, which are compatible with xiView.

To so, open the results and go to File menu -> Save -> Results. In 'Save as Type', select mzID 1.2 (or mzID 1.3).
For more details, go to our tutorial (section 2.3.4.1).

This feature will export the mzID result file as well as the raw spectra (in ms2 format).
On xiView, import both files and the fasta you used to perform the search.

Best regards,
Diogo

**Comment by rxpiyush** [comment]
@diogobor 
After exporting the file in mzID format, the xiView is showing an error when I try to upload the data because SCOUT generates multiple residue positions for single crosslink pairs (e.g. highlighted in the attached file). Can you help me how I can resolve this?
<img width="1092" alt="Screenshot 2024-08-29 at 6 35 08 PM" src="https://github.com/user-attachments/assets/10376419-31c8-4463-9708-998e08213c12">

**Comment by psharm37** [comment]
@diogobor
After exporting the file in mzID format, the xiView is showing an error when I try to upload the data because SCOUT generates multiple residue positions for single crosslink pairs (e.g. highlighted in the attached file). Can you help me how I can resolve this?
<img width="1092" alt="Screenshot 2024-08-29 at 6 35 08 PM" src="https://github.com/user-attachments/assets/3ebdf651-de2e-4da0-ac87-c56570f9df65">

**Comment by diogobor** [comment]
@psharm37 
Thanks for reporting this issue.
We're working together with xiView team to solve this problem.
Meanwhile, would it possible to send me this *.scout file? I would like to test exactly this example.

Best,
Diogo

**Comment by psharm37** [comment]
@diogobor, we are able to figure out the problem—only mzid1.2 version of saved results is working with XiView and not 1.3 version. Still, here is the *.scout file for your reference.

[PG.scout.zip](https://github.com/user-attachments/files/16897293/PG.scout.zip)

**Comment by diogobor** [comment]
@psharm37 Thanks for sending me the file.
Yes, that's true.
I've implemented mzID 1.3 and now xiView team and I are working to turn xiView compatible with mzID 1.3.

Meanwhile, export your results to mzID 1.2.

Best,
Diogo
