### ISSUE TITLE
scout search crashes immediately with digestor not found

### ISSUE THREAD

**Issue by grandrea** [diogobor/Scout#9]
Hello,

I have tried a search with scout on windows on files in .raw and .mgf format . The search crashes immediately with the following error:

I attach log and fasta file.

Thanks!

(As a generic suggestion, being able to maximise/resize window would be very, very nice!)

[Scout_log.txt](https://github.com/user-attachments/files/16613371/Scout_log.txt)
[240809_Dad_DSSOunfrac_MM_database.txt](https://github.com/user-attachments/files/16613378/240809_Dad_DSSOunfrac_MM_database.txt)

**Comment by grandrea** [comment]
Hello,
is there anything we can do to perform our searches in this case?

**Comment by diogobor** [comment]
Dear @grandrea ,

This issue happens because probably you updated the software from an older version to 1.5.1, and the digestor module was not updated. We already fixed this problem in the update feature of Scout, and we are waiting for the acceptance of the paper to release the official version of our software.

So, to try to solve this issue, you can uninstall the software (from Control Panel -> Uninstall apps), download the 1.5.1 version and install it from scratch (without any previous version installed on your computer).

Best regards,
Diogo

**Comment by diogobor** [comment]
Hello @grandrea ,

We've fixed the issues you pointed out in this thread.

Thanks for evaluating and using Scout.

Best,
Diogo
